In [1]:
#now we are learn about the data selection and filtering
import pandas as pd
print(pd.__version__)

3.0.3

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
print(df)
print(pd.__version__)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
3.0.3

In [5]:
#filtering with the conditions
df[(df["sex"]=="Male") & (df["tip"]<5)]

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
235       10.07  1.25  Male     No  Sat  Dinner     2
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[137 rows x 7 columns]

In [6]:
df[(df["total_bill"]>20)&(df["sex"]=="Female")]

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
72        26.86  3.14  Female    Yes   Sat  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
85        34.83  5.17  Female     No  Thur   Lunch     4
94        22.75  3.25  Female     No   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
114       25.71  4.00  Female     No   Sun  Dinner     3
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
131       20.27  2.83  Female     No  Thur   Lunch     2
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
186       20.90  3.50  Female    Yes   Sun  Dinner     3
197       43.11  5.00  Female    Yes  Thur   Lunch     4
214       28.17  6.50  Female    Yes   Sat  Dinner     3
219       30.14  3.09  Female    Yes   Sat  Dinner     4
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [ ]:
df.query(" sex=='Female' and time=='Lunch'")
#this is the filtering usinng the query

     total_bill   tip     sex smoker   day   time  size
82        10.07  1.83  Female     No  Thur  Lunch     1
85        34.83  5.17  Female     No  Thur  Lunch     4
117       10.65  1.50  Female     No  Thur  Lunch     2
118       12.43  1.80  Female     No  Thur  Lunch     2
119       24.08  2.92  Female     No  Thur  Lunch     4
121       13.42  1.68  Female     No  Thur  Lunch     2
124       12.48  2.52  Female     No  Thur  Lunch     2
125       29.80  4.20  Female     No  Thur  Lunch     6
127       14.52  2.00  Female     No  Thur  Lunch     2
128       11.38  2.00  Female     No  Thur  Lunch     2
131       20.27  2.83  Female     No  Thur  Lunch     2
132       11.17  1.50  Female     No  Thur  Lunch     2
133       12.26  2.00  Female     No  Thur  Lunch     2
134       18.26  3.25  Female     No  Thur  Lunch     2
135        8.51  1.25  Female     No  Thur  Lunch     2
136       10.33  2.00  Female     No  Thur  Lunch     2
137       14.15  2.00  Female     No  Thur  Lunch     2
139       13.16  2.75  Female     No  Thur  Lunch     2
140       17.47  3.50  Female     No  Thur  Lunch     2
143       27.05  5.00  Female     No  Thur  Lunch     6
144       16.43  2.30  Female     No  Thur  Lunch     2
145        8.35  1.50  Female     No  Thur  Lunch     2
146       18.64  1.36  Female     No  Thur  Lunch     3
147       11.87  1.63  Female     No  Thur  Lunch     2
191       19.81  4.19  Female    Yes  Thur  Lunch     2
197       43.11  5.00  Female    Yes  Thur  Lunch     4
198       13.00  2.00  Female    Yes  Thur  Lunch     2
201       12.74  2.01  Female    Yes  Thur  Lunch     2
202       13.00  2.00  Female    Yes  Thur  Lunch     2
203       16.40  2.50  Female    Yes  Thur  Lunch     2
205       16.47  3.23  Female    Yes  Thur  Lunch     3
221       13.42  3.48  Female    Yes   Fri  Lunch     2
223       15.98  3.00  Female     No   Fri  Lunch     3
225       16.27  2.50  Female    Yes   Fri  Lunch     2
226       10.09  2.00  Female    Yes   Fri  Lunch     2

In [ ]:
# Query are the proper text based operator like and ,or ,not the nothing use thesymobols